title: Siddhatha Devops
email: siddhartha.devops9@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
   Hello, This is Siddhartha
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  siddu71

# Build settings

theme: minima


  
#theme: minima
plugins:
  - jekyll-feed


gems:
  - jekyll-paginate

paginate: 5 # Or however many posts you want per page
paginate_path: "/page:num/"



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
